# Generated by Django 6.0.4 on 2026-04-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='color',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.CharField(default='💰', max_length=20),
        ),
    ]
